# Generated by Django 3.0.7 on 2020-07-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messengerprofile',
            old_name='last_active',
            new_name='last_interaction',
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='live_chat_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='page_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='provided_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='messengerprofile',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
