# Generated by Django 3.0.7 on 2020-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20200712_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerOrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Confirmed'), (3, 'Expired'), (4, 'Cancelled')], default=1)),
                ('item_id', models.CharField(max_length=16)),
                ('parameters', models.TextField()),
                ('contact_details', models.TextField()),
                ('provided_name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
