# Generated by Django 3.0.7 on 2020-07-14 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_messengerorderform'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerorderform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messengerorderform',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_forms', to='chatbot.MessengerProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messengerorderform',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='messengerorderform',
            name='stock_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='messengerorderform',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messengerorderform',
            name='contact_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messengerorderform',
            name='parameters',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messengerorderform',
            name='provided_name',
            field=models.TextField(null=True),
        ),
    ]
