# Generated by Django 3.0.7 on 2020-07-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200713_1432'),
        ('chatbot', '0004_auto_20200714_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengerorderform',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='messengerorderform',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='messengerorderform',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_forms', to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='messengerorderform',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_forms', to='inventory.Item'),
        ),
    ]
