# Generated by Django 3.0.7 on 2020-07-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200713_1432'),
        ('chatbot', '0005_auto_20200714_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerorderform',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_forms', to='inventory.ItemStock'),
        ),
    ]
