# Generated by Django 3.0.7 on 2020-07-05 04:54

from django.db import migrations, models
import django.db.models.deletion
import inventory.utils.uploaders


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=inventory.utils.uploaders.upload_item_photo)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
