# Generated by Django 3.0.7 on 2020-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200711_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertemplate',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='parametertemplate',
            name='parameter_type',
            field=models.CharField(choices=[('S', 'String'), ('I', 'Integer'), ('D', 'Decimal')], default='S', max_length=8),
        ),
    ]
