# Generated by Django 3.0.7 on 2020-07-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200713_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameteritemrelation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_params', to='inventory.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='parameteritemrelation',
            unique_together={('item', 'parameter'), ('stock', 'parameter')},
        ),
    ]
