# Generated by Django 3.0.7 on 2020-07-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200713_1352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameteritemrelation',
            unique_together={('stock', 'parameter', 'item')},
        ),
    ]
