# Generated by Django 3.0.7 on 2020-07-15 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_auto_20200713_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.ItemStock'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Assigned'), (4, 'For Delivery'), (5, 'Complete')], default=1),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Assigned'), (4, 'For Delivery'), (5, 'Complete')], default=1),
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
