# Generated by Django 3.0.7 on 2020-07-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200716_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='stock',
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.Order')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_orders', to='inventory.ItemStock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
