# Generated by Django 3.0.7 on 2020-07-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_messengerorderform_order'),
        ('inventory', '0012_auto_20200718_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='buyer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chatbot.MessengerProfile'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='chatbot.MessengerProfile'),
        ),
    ]
