# Generated by Django 3.0.7 on 2020-07-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20200720_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitemstock',
            name='style_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='style_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
